[project]
name = "scraping-libraries"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "aiohttp>=3.13.3",
    "asyncio>=4.0.0",
    "beautifulsoup4>=4.14.3",
    "fake-useragent>=2.2.0",
    "ipykernel==7.2.0",
    "jupyter>=1.1.1",
    "lxml[html-clean]>=6.0.2",
    "nest-asyncio>=1.6.0",
    "notebook>=7.5.3",
    "pandas>=3.0.0",
    "pandas-stubs~=3.0.0",
    "playwright>=1.57.0",
    "requests>=2.32.5",
    "requests-html>=0.10.0",
    "selenium>=4.40.0",
    "undetected-chromedriver>=3.5.5",
    "websockets==16.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.14",
    "ty>=0.0.14",
    "types-beautifulsoup4>=4.12.0.20250516",
    "types-requests>=2.32.4.20260107",
]
